### ISSUE TITLE
Call for maintainers. I need your help

### ISSUE THREAD

**Issue by tomchentw** [tomchentw/react-google-maps#266]
> Original contents from https://github.com/cristiandley/react-gl-maps/issues/6#issuecomment-222048760

Hi guys,

First, I want to apologize for not being active on maintaining the module, `react-google-maps`. The main reason is that I don't have any production projects using it for a year and more. Plus, the overhead of the issues and lack of documentations making it even harder to keep issues clean.

I should have asked the great guys like @cristiandley and others for help in order to keep the community healthy. So, here's what I'm gonna to do,

1. Add "Call for maintainers" section in `README.md`.
2. Review current PRs ASAP, merge it if possible and release minor/patch version
3. Create guidelines for maintaining the repo/commit messages/release process……etc
4. Add contributors to the repository. @cristiandley and anyone else?
5. Review on the fork (react-gl-maps) to see if we can merge them together.

Please let me know what you think guys. Also, feel free to reach me out via my email (you can see it on my GitHub profile) if I'm not responding. Sometimes email of issues get lost in my inbox.

Thank you guys for all the hard work!

**Comment by cristiandley** [comment]
You have my sword on this path! :smile:

**Comment by rewop** [comment]
I can help, also due to the fact I got to know the module a little bit better later.

**Comment by tomchentw** [comment]
## TODOs

* [ ] Add "Call for maintainers" section in `README.md`.
* [ ] Review current PRs ASAP, merge it if possible and release minor/patch version
* [ ] Create guidelines for maintaining the repo/commit messages/release process……etc
* [ ] Add contributors to the repository. @cristiandley and anyone else?
* [ ] Review on the fork (react-gl-maps) to see if we can merge them together.

---
WIP

**Comment by WebRuin** [comment]
I would like to be a maintainer as well.  How can I help?  What needs doing?

**Comment by zaggy** [comment]
HI, I would be happy to help. Can I just choose an open bug and work on it?

**Comment by tomchentw** [comment]
@zaggy sure. I'd suggest you open a new ticket and points to those old tickets in it :)

**Comment by idolize** [comment]
@tomchentw I'm happy to help too

**Comment by tomchentw** [comment]
@idolize Thank you so much!

**Comment by davidpelayo** [comment]
@tomchentw I'm happy to help too!

**Comment by tomchentw** [comment]
@davidpelayo sure. Feel free to pick some topics in this thread to work on it!

**Comment by tiagomegas** [comment]
@tomchentw I'm thinking on helping you out too! And let me add that you when you say no project uses in production...we use it here: www.flykt.com !!! And I love it ^^

**Comment by tomchentw** [comment]
@tiagomegas thanks. Check out [6.0.0](https://github.com/tomchentw/react-google-maps/issues/318) which is released on npm beta tag now. We also have a new demo page. Feel free to try it:
https://tomchentw.github.io/react-google-maps/

**Comment by thzinc** [comment]
I'd be interested in helping to maintain this project. At Syncromatics, we're building out a new version of our site on top of this, and I'd like to be able to contribute improvements and help do the work of maintaining the codebase. How can I go about contributing? (I do already have a PR out for adding TrafficLayer)

(CC @wuct @cristiandley @rewop)

**Comment by jsmapr1** [comment]
Happy to help also. I'm going to be using the project heavily for at least the next year so I'lll be around quite a bit.

**Comment by harlannorth** [comment]
I work with @thzinc  over at Syncromatics and as he mentioned we're using react-google-maps for the next version of our UI, so I'd like to contribute where I can as well.

**Comment by oshalygin** [comment]
Happy to help guys.  Going to be using this or something very close to it over the next couple of years.

**Comment by yoihito** [comment]
Hi guys. I would like to help you with it, going to use the project for the next year or so :)

**Comment by oshalygin** [comment]
Ive got other commitments but I havent heard back from the author(no email response :( ), I'll be ramping up on this again come March if anyone wants to fork and continue

**Comment by oshalygin** [comment]
Hey guys, there are a series of PR's that we can merge in and keep contributing to the project.  @tomchentw any chance you can grant me access?

**Comment by stereobooster** [comment]
There are 4 options for React Google maps. I created gist to compare them https://gist.github.com/stereobooster/13a26188d4ad5382bc6da9ffe76ce3e1. None of them actively supported :/.

**Comment by faviouz** [comment]
@stereobooster Yeah, because of that I ended up using react-leaftlet, which is well documented and fairly active.

**Comment by ZaynMalloc** [comment]
Hello, I would like to help out!

**Comment by shinzui** [comment]
What's the status of this?

**Comment by oshalygin** [comment]
of which @shinzui ?  We are still looking for maintainers and pushing the project forward.  @tomchentw has actually been fairly active helping out quite a bit.

**Comment by shinzui** [comment]
@oshalygin, sorry for the vague question. I'm picking a library to integrate google maps into my react app and saw the call for maintainers in the readme linking to this issue. The issue was opened 15 months ago so I was wondering if the project is going to have a maintainer steering it forward.

**Comment by oshalygin** [comment]
@shinzui There are a number of maintainers that are keeping the project alive and we are constantly releasing new features with the help of the community 👍 

Once we get some of the bigger pieces together with the project we'll cleanup the README a bit to remove ambiguity 💯

**Comment by sudheerDev** [comment]
@oshalygin Are there any API docs?. All I could see are examples and with recompose. For example, i am trying to figure out what `withScriptjs` does. Digging into the source for every import is an over kill. 
API Documentation would be great and if possible library agnostic examples.

**Comment by tomchentw** [comment]
@sudheerDev the API docs for a component is documented in the `react-styleguidist` site. Click "PROPS & METHODS" to open it. Basically, you can see it's a simple delegation to the Google Maps JavaScript API.
https://tomchentw.github.io/react-google-maps/#!/GoogleMap

![screenshot-2017-9-15 googlemap react google maps style guide](https://user-images.githubusercontent.com/922234/30472422-e0d5795a-9a2e-11e7-9e8b-44932819b7f0.png)

Yeah, currently we don't have docs for `withGoogleMaps` and `withScriptjs`, but the examples should be self-explainable. Please feel free to contribute the docs into the repo.

**Comment by sudheerDev** [comment]
@tomchentw Aah ok. Thanks. Just took time to figure out from examples, issues that few are components and few are higher order functions. Logs helped though 

Nice work with the repo!

**Comment by tomchentw** [comment]
For anyone interested, feel free to jump in answering questions on StackOverflow first:
https://stackoverflow.com/search?tab=newest&q=react-google-maps

**Comment by urikphytech** [comment]
Hi! What's the status on this issue? I'm currently working on a fork of the project but would be happy to be added as a maintainer/contributer instead.

**Comment by JustFly1984** [comment]
I'm also working on the fork, it will be ready this week, it does supports last API version, does not have componentWillMount - it uses getDerivedStateFromProps, does support all new features, and properly typed with prop-types (look ma, no PropTypes.any!), supports to load unlimited number of maps on the same page, has no lodash in dependencies and very lightweight and performant. I will publish it soon.

**Comment by JustFly1984** [comment]
@urikphytech if you want to join, I can give you access to the repo.

**Comment by urikphytech** [comment]
@JustFly1984 That sounds amazing! I'd be glad to get access and help out with your open issues/tasks. I did some work on switching to the new context API, but right now it depends on react v16.5 because it's using Class.contextType.

This is actually  my work account, better invite @uriklar which is my personal account

**Comment by JustFly1984** [comment]
@urikphytech new context api doesn't help if you need multiple maps on the same page. I've fixed this issue. I will add you to collaborators. Please do your changes in separate branch, and make pull requests. Do you have skype or something?

**Comment by JustFly1984** [comment]
@urikphytech I've added you to collaborators, lets continue conversation here https://github.com/JustFly1984/react-google-maps-api/invitations

It is private repo, cos I use my own key to test development. There is an example build on gatsby (so I could test SSR later on)

**Comment by lucifer1004** [comment]
I am working on a new React wrapper for Google Map API, based on the latest React features: hooks, context...
The library has only three direct dependencies: `react`, `react-dom` and `loadjs`

Current status:
- MapBox
- Marker
- InfoWindow
- Polygon
- HeatMap
- OverlayView

Highlights:
- No class components
- Highly flexible. Components can be put anywhere inside the context, which makes it much easier to  implement complicated interactions or logic.
- 100% coverage (not that good, using many mocks)

@urikphytech @JustFly1984 it is possible to have multiple maps on the same page with context. You only need to use multiple contexts.

[My Repo](https://github.com/lucifer1004/react-google-map)
APIs are not fully stable yet, and I hope more people can join.

**Comment by JustFly1984** [comment]
@lucifer1004 we have a stable API at `@react-google-maps/api`

**Comment by urikphytech** [comment]
Btw you can check out the hooks branch. It has a working poc of the useMapComponent hook

We would love you to join us! We want to start adding test as well soon so it would be great to get you on board working on that
